### ISSUE TITLE
Unable to alter stack trace.

### ISSUE THREAD

**Issue by reggi** [bjyoungblood/es6-error#11]
I have a custom error object and I've built in the ability to set and update message along with the stack trace.

https://github.com/reggi/error-suite/blob/master/src/multi-error.js#L27

It seems like you've locked any changes to `this.stack` from your end so It's read-only for me. 

http://stackoverflow.com/questions/36986345/typeerror-stack-is-read-only

Can you update this so I can update the message in my stack trace?

**Comment by bjyoungblood** [comment]
Published v2.1.1 to npm.

**Comment by reggi** [comment]
WOW WOW WOW WOW WOW WOW WOW WOW WOW WOW WOW Thanks!
