### ISSUE TITLE
babel config causes error with React Native

### ISSUE THREAD

**Issue by tyscorp** [bjyoungblood/es6-error#19]
Having the "babel" key in package.json seems to throw an error when required from React Native.

The specific error is:

```
ReferenceError: Unknown plugin "add-module-exports" specified in "node_modules/es6-error/package.json" at 0, attempted to resolve relative to "node_modules/es6-error"
```

Fixing this should be as simple as moving the config to a .babelrc file.

**Comment by bjyoungblood** [comment]
Fixed by #20 (v3.0.1).
