### ISSUE TITLE
Breaking changes for 4.1.0 behavior

### ISSUE THREAD

**Issue by roderickhsiao** [bjyoungblood/es6-error#37]
Test cases

```
import ExtendableError from 'es6-error`;

class A extends ExtendableError {
  super('foo');
  this.name = 'bar';
} 

const errorA = new A();
console.log(errorA instanceof A)
```

On version 
`4.0.2` https://gist.github.com/tinder-rhsiao/aaa1082eb6575b7ee6f591f958adec61 will return `true`
`4.1.0` https://gist.github.com/tinder-rhsiao/e8c7a1255f3def0ad4a72200a2c91dae returns `false`

doesn't seems `transform-builtin-extend` is outputting as is, not sure if it is expected.

**Comment by tinder-rhsiao** [comment]
https://github.com/babel/babel/issues/3083

**Comment by roderickhsiao** [comment]
https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend/issues/14

**Comment by bjyoungblood** [comment]
It does look like `transform-builtin-extend` was not being applied. I published v4.1.1 as a fix.

**Comment by roderickhsiao** [comment]
Thanks for the prompt reply, verify the fix 🎇

**Comment by cyrilchapon** [comment]
Where is `transform-builtin-extend` you are talking about ?

I tried `npm install @babel/transform-builtin-extend` and `npm install @babel/plugin-transform-builtin-extend` but it didn't work

**Comment by bjyoungblood** [comment]
The package name on npm is [`babel-plugin-transform-builtin-extend`](https://www.npmjs.com/package/babel-plugin-transform-builtin-extend) ([Github link](https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend)). It's not owned or maintained by the Babel team.

**Comment by cyrilchapon** [comment]
Ok thanks bud @bjyoungblood 

To finish on that topic, do you know if, nowadays, babel 7 is natively handling this correctly ?

(I have 2 apps, on with old school babel and one with pretty recent release, and wish I knew the status of this)

**Comment by bjyoungblood** [comment]
It looks like this was added in babel/babel#7020, but might not be bug-free yet (see babel/babel#7506).

FWIW, I tried compiling es6-error with Babel 7 (and no `transform-builtin-extend`). All the tests passed, and the output seemed to work fine under Node v9.9, but YMMV.

**Comment by cyrilchapon** [comment]
Ok thanks for your help ☺️
